### ISSUE TITLE
New GUI with better User Exp.

### ISSUE THREAD

**Issue by Jowat97** [lkmvip/netflix-4K-DDplus#30]
Hello @lkmvip,

I have rewritten the GUI with following changes:

1. You can edit the settings by clicking the icon and do not have to go to the option menu.
2. A dark theme, which fits to the dark theme from Netflix.
3. You now can click the label, and do not have to click the checkbox in the settings.
4. Renamed and edited a few strings.

You can see it in the GIF:

![Super Netflix 4K](https://user-images.githubusercontent.com/45443409/117558900-3c11c780-b081-11eb-8a7a-96eb9d0ef21f.gif)

Some additional thoughts:
1. I renamed it to a more specific name, but you can of course keep your original name.
2. To support open source projects, I think GPLv3 is better then MIT License. But it's totally up to you.
3. I don't know if the function of "Edge spoofing" is necessary, since this extension is for Edge only. And other browsers like Chrome, Firefox etc. can't support 4K, since they don't support HEVC Codec. So probably you want to remove this function.

Source Code: [Super Netflix 4K.zip](https://github.com/lkmvip/netflix-4K-DDplus/files/6446854/Super.Netflix.4K.zip)
(You can install it, be dropping it in the extensions site from Edge, but extensions from third party need to be enabled)

If you like it, take the things you would like to have. It's up to you what you want to take and what not. =]
Feel free to give me some feedback/suggestions etc! 👍 

Best Regards!

**Comment by lkmvip** [comment]
Thank you for your work, this is a great feature, I will merge it into master

Regarding the use of MIT,
First of all, because I refer to https://github.com/truedread/netflix-1080p, out of respect for him, I continue to use MIT.

Of course, the main thing is that I am very lazy, I just want to simply use extensions, but don’t want to develop in depth.

Similarly, because of MIT, you can do whatever you want:)



About disguising as EDGE
EDGE is a uwp application, in win10 ver<1909
Netflix created a different identification code for it. Earlier, EDGE (Chromium core) was not stable, and sometimes 4K could not be played. It needed to be disguised as UWPEDGE to play, so this option was provided, but with the efforts of Netflix and MS , Now, EDGE (Chromium core) is very stable, so I have also removed this option in the latest version.

**Comment by Jowat97** [comment]
Thank you for your fast reply! Totally unterstand your arguments.
Glad to hear, that you like this GUI! 👍
