### ISSUE TITLE
error D7355....

### ISSUE THREAD

**Issue by DukeHuangWP** [lkmvip/netflix-4K-DDplus#4]
error D7355....

**Comment by Invictaz** [comment]
Same (Windows 7) @lkmvip

**Comment by lkmvip** [comment]
windos 10 only 

win7 is no drm 

if you win7 ,you can use Chrome and this https://github.com/truedread/netflix-1080p

**Comment by Invictaz** [comment]
@lkmvip that is outdated see the issue I posted. It should also work with Win 7.

**Comment by lkmvip** [comment]
I am not going to make this extension compatible with non-win10, although it is very simple, but it is not necessary, because this is repeated with the Chrome extension, because the function and effect of the extension can be the same in the widevine DRM environment

If you plan to watch Netflix on PC, please use win10, don't look for other solutions, use win10 is the best solution.

**Comment by Invictaz** [comment]
Unfortunately I cannot upgrade to Windows 8 or 10 in this environment.

**Comment by lkmvip** [comment]
If you are not using WIN10, then I cannot help you.

This extension only works on WIN10.
