### ISSUE TITLE
4K and HEVC only work using HDR or Netflix app

### ISSUE THREAD

**Issue by ReneSchimmelpfennig** [lkmvip/netflix-4K-DDplus#66]
4K and the HEVC codec don't work on SDR displays. Maximum of 1080p and AVC works. DRM requirements are met, the Netflix app from the Windows store correctly works in 4K, but sadly is missing good quality audio options such as Dolby Atmos.

**Comment by Antivan28** [comment]
Its an old bug when watching on Edge actually.  I first discovered it when rewatching  Breaking Bad  in 2021-2022.  The show was in 4k when i watched yearly seasons and then suddenly 1080p, older seasons which was in 4k (hevc) became 1080p (avc)  but Netflix app still have an 4k version.   The thing is that it only affect 4k videos that  a) not hdr or you turn hdr off in windows settings  b) 4k videos which use only Hevc codec without prk.  (like breaking bad)  But foe other 4k videos like Old ways movie is still 4k on Edge because it uses  prk alongside Hevc codec.      This bug has nothing to do with this  extension by the way,  but  would be nice if its possible to edit cadmium to acuall have 4k playback on all supported videos like in Netflix app.     As workaround i suggest to enable  HDR even if ots just a gimmick in you monitor,  because that way most Netflix original 4k contect will kick off with Hevc, HDR, PRK combo and have a proper 4k playback.

**Comment by lkmvip** [comment]
fixed
use option "Focus 4K SDR"
