### ISSUE TITLE
[Bug] Switching to DDP 2.0 audio crashes Netflix

### ISSUE THREAD

**Issue by Sparoney** [lkmvip/netflix-4K-DDplus#7]
Hey,

Thanks so much for implementing the AVC option!! You're amazing.

I have however noticed a bug since the last release I forgot to mention. When enabling Dolby Digital Plus tracks, switching from English DDP 5.1 to English DDP 2.0 crashes Netflix with the following error (haven't tried other languages but I'm assuming its the same error): 

![image](https://user-images.githubusercontent.com/38852913/88813226-012e5980-d1fc-11ea-9172-737fffb691e5.png)

I tested this with the original Kissing Booth movie.

I've also noticed on the bitrate menu, with DDP 5.1, the audio bitrate goes up to 640 but is locked at 192. Do you know how to fix that or if its some weird limitation? It does this in the Windows 10 app too.

No rush about this please take your time, just thought I'd let you know this happens. (By the way, I am using 1080p not 4K).

**Comment by lkmvip** [comment]
Q1, Yes, it is because of the error caused by calling AAC and DDLPUS at the same time. After removing the call of AAC, the error will not be thrown.

Q2,I have no way to deal with this problem. If you use the old method to force 640bit, it will fail when Netflix updates the playback core. Now the core has been updated. If you really need it, you can add `u.push("heaac-5.1-dash");` in line 64275 of cadmium-playercore-6.0023.976.031.js,It will force call 640bit.

**Comment by lkmvip** [comment]
After my test, Atmos can only be locked at 768bit, while DDplus can only work at 192bit.

In the new playback core


![12333](https://user-images.githubusercontent.com/12974141/89205858-f3f1e000-d5ea-11ea-888e-d0d4e1b5a18b.png)

**Comment by Sparoney** [comment]
Tested and works. Thank you so much <3
