### ISSUE TITLE
Error code UI3013

### ISSUE THREAD

**Issue by redHat-arko** [lkmvip/netflix-4K-DDplus#77]
![Screenshot (20)](https://github.com/lkmvip/netflix-4K-DDplus/assets/72915590/c37601de-db8e-4246-ad01-a7cf08ff557b)

Netflix throws up an error code UI3013 when the extension is enabled an as a result, nothing can be played. Disabling the extension resumes playback as normal (but without any of the perks provided by the extension in the first place. Checked on both Edge and Chrome.

**Comment by lkmvip** [comment]
The current extension can be used in win11 23H2. Check it yourself. If it is still the case, reset Windows.

To reset your PC, go to Start > Settings > Update & Security > Recovery > Reset this PC > Get Started

**Comment by serialpotato** [comment]
> The current extension can be used in win11 23H2. Check it yourself. If it is still the case, reset Windows.
> 
> To reset your PC, go to Start > Settings > Update & Security > Recovery > Reset this PC > Get Started

Hi mate, it's not related to Windows version. The error is due to extension. When extension is disabled, the same content plays fine without the error. May be the extension needs an update or something to fix this problem. Other netflix extensions are also experiencing the same issue. Please see the following reddit thread for details:

https://www.reddit.com/r/netflix/comments/tvd45s/error_ui3013/

**Comment by lkmvip** [comment]
I have already said that I can use it. If you can't use it after resetting it as I just said, then I can't help you. In fact, if Netflix bans chrome&edge extensions, I will definitely not oppose them. If necessary, I will immediately terminate this REPO.

**Comment by serialpotato** [comment]
> I have already said that I can use it. If you can't use it after resetting it as I just said, then I can't help you. In fact, if Netflix bans chrome&edge extensions, I will definitely not oppose them. If necessary, I will immediately terminate this REPO.

Mate, I think its due to the playercore update. I can successfully use the following extension which patches the playercore on the fly and enables 1080p mode:

https://github.com/DavidBuchanan314/Turbo-Recadmiumator

But it doesn't have AVC, or DDPlus like your extension. I know its working fine at your end but the windows resetting and netflix errors don't seem to be related when its happening due to the extensions. I am pretty certain Netflix updated the playercore which is why the extension that patches it on the fly continues to work but the one that uses old version doesn't.

**Comment by lkmvip** [comment]
I say it again, the playback core of REPO can be used now. If you can't use it, that's your problem. I'm Win11.22H2. If you're not, I can't help you. If you are, reset your Windows. Don't tell me anything. I can't find problems on my computer, and I can't fix them. It's annoying, so I close this issue. Maybe I should just close REPO.
